spring:
    application:
        name: inventory-service
    cloud:
        config:
            profile: dev
    config:
        import: configserver:http://localhost:8888
springdoc:
    group-configs:
        - group: ${spring.application.name}
          paths-to-match:
              - /api/**
