spring:
  application:
    name: config-server
  profiles:
    active: ${CONFIG_SERVER_BACKEND:native}
  cloud:
    config:
      server:
        default-label: ${CONFIG_SERVER_GIT_LABEL:main}
        native:
          search-locations: classpath:/config-repo
        git:
          uri: ${CONFIG_SERVER_GIT_URI:file:${user.dir}}
          clone-on-start: ${CONFIG_SERVER_GIT_CLONE_ON_START:false}
springdoc:
  group-configs:
    - group: ${spring.application.name}
      paths-to-match:
        - /api/**
        - /actuator/**
server:
  port: ${CONFIG_SERVER_PORT:8888}
management:
  endpoints:
    web:
      exposure:
        include: health,info,env,prometheus
